mascots = [
#            City              Mascot
         [ "ATLANTA",          "HAWKS"        ],
         [ "BROOKLYN",         "NETS"         ],
         [ "BOSTON",           "CELTICS"      ],
         [ "CHARLOTTE",        "HORNETS"      ],
         [ "CHICAGO",          "BULLS"        ],
         [ "CLEVELAND",        "CAVALIERS"    ],
         [ "DALLAS",           "MAVERICKS"    ],
         [ "DENVER",           "NUGGETS"      ],
         [ "DETROIT",          "PISTONS"      ],
         [ "GOLDEN STATE",     "WARRIORS"     ],
         [ "HOUSTON",          "ROCKETS"      ],
         [ "INDIANA",          "PACERS"       ],
         [ "LA",               "CLIPPERS"     ],
         [ "LOS ANGELES",      "LAKERS"       ],
         [ "MEMPHIS",          "GRIZZLIES"    ],
         [ "MIAMI",            "HEAT"         ],
         [ "MILWAUKEE",        "BUCKS"        ],
         [ "MINNESOTA",        "TIMBERWOLVES" ],
         [ "NEW ORLEANS",      "PELICANS"     ],
         [ "NEW YORK",         "KNICKS"       ],
         [ "OKLAHOMA CITY",    "THUNDER"      ],
         [ "ORLANDO",          "MAGIC"        ],
         [ "PHILADELPHIA",     "SIXERS"       ],
         [ "PHOENIX",          "SUNS"         ],
         [ "PORTLAND",         "BLAZERS"      ],
         [ "SACRAMENTO",       "KINGS"        ],
         [ "SAN ANTONIO",      "SPURS"        ],
         [ "TORONTO",          "RAPTORS"      ],
         [ "UTAH",             "JAZZ"         ],
         [ "WASHINGTON",       "WIZARDS"      ],
]
